### ISSUE TITLE
Docker Pull Command Failed for setting up Controller

### ISSUE THREAD

**Issue by slarimore02** [vmware/te-ns#20]
From the swagger interface for setting up the controller it currently fails to pull the docker image with the default container image - projects.registry.vmware.com/tens/te:v2.0. A docker pull for this same image succeeds without error. 

API Call:

root@ubuntu-test:/opt/ten-ns/te# curl -vvv -X GET "http://10.206.114.251:4000/api/setup_te?te_controller_ip=10.206.114.251&user=ubuntu&passwd=ubuntu&dockerhub_repo=projects.registry.vmware.com%2Ftens%2Fte%3Av2.0" -H  "accept: */*"
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 10.206.114.251:4000...
* TCP_NODELAY set
* Connected to 10.206.114.251 (10.206.114.251) port 4000 (#0)
> GET /api/setup_te?te_controller_ip=10.206.114.251&user=ubuntu&passwd=ubuntu&dockerhub_repo=projects.registry.vmware.com%2Ftens%2Fte%3Av2.0 HTTP/1.1
> Host: 10.206.114.251:4000
> User-Agent: curl/7.68.0
> accept: */*
> 
* Mark bundle as not supporting multiuse
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Content-Type: application/json
< Content-Length: 62
< Server: Werkzeug/1.0.1 Python/3.8.5
< Date: Sun, 09 May 2021 01:10:38 GMT
< 
{"status":false,"statusmessage":"docker pull command failed"}
* Closing connection 0

**Comment by aravindhank11** [comment]
Hi @slarimore02 

The failure is propagated from https://github.com/vmware/te-ns/blob/main/te/GET_AND_RUN_DOCKER_IMAGE.py#L286-L294. 

Please check the logs at `/home/ubuntu/download_docker.log` -- It is highly likely that the ubuntu user does not have docker privileges. You must see logs similar to:
```
2021-05-09 04:26:30,727 - init - DEBUG - Running command 'docker pull projects.registry.vmware.com/tens/te:v2.0'
2021-05-09 04:26:30,989 - init - DEBUG - ERROR in downloading dockerhub image Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/images/create?fromImage=projects.registry.vmware.com%2Ftens%2Fte&tag=v2.0: dial unix /var/run/docker.sock: connect: permission denied
```

I was also able to locally reproduce the issue, by using a user who is not a part of docker group. Please follow the below commands (or) refer to the official docker documentation to add your user to the docker group. Alternatively you can use `root` user who has the default set of permissions to the docker group.

How to give docker permissions to a user:
```
 sudo groupadd docker
 sudo usermod -aG docker $USER
 ```
 
Ref: https://docs.docker.com/engine/install/linux-postinstall/

**Comment by aravindhank11** [comment]
If the above works, you can further use TENS by redirecting to the output's `te_controller_swagger_ui_url` or refer to https://github.com/vmware/te-ns/blob/main/how_to_use/TENS_IN_WRITE_ACCESS.md (better tested) to use.

If you follow TENS_IN_WRITE_ACCESS.md, please feel free to skip setup_te() API as you had already setup_te() using the swagger interface.

**Comment by slarimore02** [comment]
That was the issue thank you!
