### ISSUE TITLE
building on ubuntu 20.04 src/te_agent.c:43:10: fatal error: json/json.h: No such file or directory

### ISSUE THREAD

**Issue by andreireiand** [vmware/te-ns#33]
~/tens/te-ns/te_dp$ sudo make clean
Cleaned the binaries of TE's DP and Stat collector
master@ubnt:~/tens/te-ns/te_dp$ sudo make all
Linked src/te_metrics.c Successfully
Linked src/te_utils.c Successfully
src/te_agent.c:43:10: fatal error: json/json.h: No such file or directory
   43 | #include <json/json.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:63: obj/te_agent.o] Error 1

**Comment by aravindhank11** [comment]
Hi @andreireiand,

The entire build process is containerized. You could build the docker image following instructions at: https://github.com/vmware/te-ns/blob/main/BUILD.md.

However, having said this, the TENS container image is already built and hosted in the harbor (the equivalent of docker-hub) and ready to use. Please refer to https://github.com/vmware/te-ns/blob/main/how_to_use/TENS_IN_WRITE_ACCESS.md to kick start usage.

**Comment by aravindhank11** [comment]
@andreireiand  please close the issue if you are contented with the response

**Comment by aravindhank11** [comment]
Closing the issue due to inactivity. @andreireiand please reopen if you would like additional help
