### ISSUE TITLE
No setup.sh in te_dp/

### ISSUE THREAD

**Issue by dipmaji22** [vmware/te-ns#52]
### Describe the bug

"Compiling the datapath process" mentions going to te_dp/ and running setup.sh to install the necessary libraries, but there is no such file in the directory.

### Reproduction steps

1. Clone the repo
2. Go to te_dp/
3. No setup.sh file present

### Expected behavior

setup.sh should be available

**Comment by aravindhank11** [comment]
setup.sh is located here: https://github.com/vmware/te-ns/blob/main/te/tedp_docker/setup.sh

We should fix the readme, rather.

@dipmaji22, could you please refer to https://github.com/vmware/te-ns/blob/main/BUILD.md for building? 

We support dockerized build and deployment.

In an ideal case, you wouldn't even need to build anything. You could follow steps in https://github.com/vmware/te-ns/blob/main/how_to_use/TENS_IN_WRITE_ACCESS.md to get a docker image deployed and ready to run.

**Comment by dipmaji22** [comment]
Ok, got it. Thanks for the help.
Please fix the readme, and please feel free to close the issue.

**Comment by aravindhank11** [comment]
@sanathpholla could you please help with the README fix? 
CC: @sudks
