### ISSUE TITLE
TE build process fails due to PostgresSQL repo xenial-pgdg being deprecated

### ISSUE THREAD

**Issue by priyadarshitathagat** [vmware/te-ns#57]
### Describe the bug

The postgresSQL repo xenial-pgdg has been deprecated and we have a dependency on our TE-NS build.
The builds will fail...
```
W: The repository 'http://apt.postgresql.org/pub/repos/apt xenial-pgdg Release' does not have a Release file.
E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/xenial-pgdg/main/binary-amd64/Packages  404  Not Found [IP: 217.196.149.55 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package postgresql-11
sed: can't read /etc/postgresql/*/main/pg_hba.conf: No such file or directory
gpasswd: user 'postgres' does not exist
chown: invalid group: 'root:ssl-cert'
chmod: cannot access '/etc/ssl/private/ssl-cert-snakeoil.key': No such file or directory
https://www.postgresql.org/download/linux/ubuntu/
```
we are looking for workarounds currently... else we might have to move to 18.04

### Reproduction steps

start the build 
`./build_te.sh` 

### Expected behavior

The build should work fine.

### Additional context

cc: @aravindhank11 - let us know if it's the best to move to 18.04.

**Comment by aravindhank11** [comment]
I would very much recommend moving to Ubuntu 22.04. Ubuntu16 has long been discontinued for support.

Challenges I see for OS upgrade:
1) Most of the python code is already python3 compatible, but expect breakages w.r.t packages from 3.10 version
2) Make sure the 22 docker works with various underlying OS
3) TE allows configuration of DNS on host. This was a challenge internal to VMware as well. Samar Yadav might be able to provide with deeper insights on the same.

But the code changes must be very contained within the Dockerfiles.

CC: @vipinpr5991, @sudks, @sanathpholla

**Comment by priyadarshitathagat** [comment]
Thanks for the inputs @aravindhank11. This would be very helpful.
